server:
  port: 8086
security:
  oauth2:
    client:
      client-id: SSO_CLIENT1
      client-secret: 123456
      user-authorization-uri: http://localhost:8088/auth/oauth/authorize
      access-token-uri: http://localhost:8088/auth/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8088/auth/oauth/token_key
